name: Semgrep SAST scan

#on:
  #workflow_dispatch: {}
  #pull_request:
    #push:
      #branches:
      #- master
      #paths:
      #- .github/workflows/SAST/semgrep.yml
    #types:
      #- opened
on:
  workflow_run:
    workflows: ["Main forkflow"]
    types:
      - completed
  
  schedule:
  - cron: 00 01 * * *

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
