name: Containers Scanning Clair Vulnerability Database Update

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 6 * * *'

jobs:

  docker:
    runs-on: ubuntu-22.04

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Run Clair Vulnerability Database update
        uses: quay/clair-action@v0.0.8
        with:
          db-file: vulnerabilityDatabase.db
          mode: update

      - name: Cache Database
        uses: actions/cache@v4.0.2
        with:
          path: vulnerabilityDatabase.db
          key: vulnerabilityDatabase.db
