name: Vulnerabilities Scanning Trivy

on:
  workflow_run:
    workflows: ["Development main workflow"]
    types: completed
  workflow_dispatch:
        
jobs:
  vulnerabilities-scanning-sarif:
    name: trivy-sarif
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          scanners: 'vuln,secret,config'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3.25.3
        with:
          sarif_file: 'trivy-results.sarif'
