name: Secret Scanning Gitleaks

on:
  pull_request:
    types: opened
  workflow_dispatch:

jobs:
  secret-scanning:
    name: git-leaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
