name: Secret Scanning Gitleaks

on: [push, workflow_dispatch]

jobs:
  scan:
    name: git-leaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
