name: Static Application Securiry Test (SAST) Semgrep

on:

  workflow_run:
    workflows: ["Development main workflow"]
    types: completed

  workflow_dispatch:
    
jobs:

  sast:

    name: semgrep
    runs-on: ubuntu-24.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4.1.4
    - run: semgrep ci --sarif --sarif-output=./Reports/semgrep-scan-result.sarif

    - name: Upload sarif results for Semgrep scan
      uses: github/codeql-action/upload-sarif@v3.25.3
      with:
        sarif_file: ./Reports/semgrep-scan-result.sarif
