name: Secret Scanning Gitleaks

on:
  pull_request:
    types: opened
  workflow_dispatch:

jobs:
  secret-scanning:
    name: git-leaks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  secret-scanning-sarif:
    name: git-leaks-sarif
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - name: Install Gitleaks CLI tool
        run: |
          git clone https://github.com/gitleaks/gitleaks.git
          cd gitleaks
          make build
          mv gitleaks /usr/local/bin
      - name: Run Gitleaks
        run: gitleaks detect --source . --report-format sarif --report-path Reports/gitleaks-scan-result.sarif
      - name: Upload sarif results for Gitleaks scan
        uses: github/codeql-action/upload-sarif@v3.25.3
        with:
          sarif_file: ./Reports/gitleaks-scan-result.sarif
