name: Secret Scanning Gitleaks

on:
  pull_request:
    types: opened
  workflow_dispatch:

jobs:
  secret-scanning:
    name: git-leaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
