name: Vulnerabilities Scanning Trivy

on:
  workflow_run:
    workflows: ["Development main workflow"]
    types: completed
  workflow_dispatch:
        
jobs:
  vulnerabilities-scanning-sarif:
    name: trivy-sarif
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          scanners: 'vuln,secret,config'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
    
  vulnerabilities-scanning-trivy-cli:
    name: trivy-cli
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          path: app

      - name: Downlod Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
      
      - name: Install Trivy
        run: |
          sudo dpkg --install trivy_0.18.3_Linux-64bit.deb
      
      - name: Run Trivy
        run: |
          trivy image app
      