name: Software Composition Analysis (SCA) - Snyk

on:

  workflow_run:
    workflows: ["Secret Scanning Gitleaks"]
    types: completed

  workflow_dispatch:

jobs:

  snyk:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - uses: actions/checkout@v4.1.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0

      - name: Restore dependencies
        run: dotnet restore ./TodoApi.sln

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: 
            --file=TodoApi.sln
            --sarif-file-output=snyk-scan-result.sarif

      - name: Upload SARIF results for Snyk scan
        uses: github/codeql-action/upload-sarif@v3.25.3
        with:
          sarif_file: snyk-scan-result.sarif
