name: Static Application Securiry Test (SAST) Semgrep

on:
  workflow_run:
    workflows: ["Software Composition Analysis (SCA) - Snyk"]
    types:
      - completed
  workflow_dispatch:

jobs:
  sast:
    name: semgrep
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
