name: Containers Scanning Clair

on:
  workflow_run:
    workflows: ["Development main workflow"]
    types: completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: todo-api
  GITHUB_LOGIN: ${{ github.actor }}
    
jobs:
  clair:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
        - name: Grab cache Clair Vulnerability Database
          uses: actions/cache@v4.0.2
          with:
            path: vulnerabilityDatabase.db
            key: vulnerabilityDatabase.db

        - name: Run Clair for todo-api Docker image
          uses: quay/clair-action@v0.0.8
          with:
            image-ref: ${{ env.REGISTRY }}/${{ env.GITHUB_LOGIN }}/${{ env.IMAGE_NAME }}:latest
            db-file: vulnerabilityDatabase.db
            format: sarif
            output: clair-scan-result.sarif
    
        - name: Upload sarif results for todo-api Docker image Clair scan
          uses: github/codeql-action/upload-sarif@v3.25.3
          with:
            sarif_file: clair-scan-result.sarif
