name: Development main workflow

on:

  pull_request:
    types: opened

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: todo-api
  GITHUB_LOGIN: ${{ github.actor }}

jobs:
  # TODO GitHub Actions: Fix all warnings from the GitHub Actions runner, example: https://github.com/kocurc/TodoApi-main/actions/runs/8961996949
  build-and-test-solution:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Checkout solution code
      uses: actions/checkout@v4.1.4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0'

    - name: Build solution
      run: dotnet build TodoApi.sln --configuration Release

    - name: Test solution
      run: dotnet test TodoApi.sln --configuration Release --no-build

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to GitHub Container Registry - ghcr.io
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image of TodoApi
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./TodoApi/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.GITHUB_LOGIN }}/${{ env.IMAGE_NAME }}:latest
        build-args: |
          OUTPUT_PATH='/Out'

  build-and-publish-images:
    runs-on: ubuntu-22.04
    if: success()
    needs: build-and-test-solution
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4.1.4
        