name: Main forkflow
run-name: Called by ${{ github.actor }}

on:

  push:
    branches:
      - 'dev/**'

  pull_request:
    types:
      - opened

jobs:

  build-and-test-solution:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:

    - name: Print the job trigger
      run: echo "The job was triggered by ${{ github.event_name }}"
      
    - name: Print operation system
      run: echo "Operation system is ${{ runner.os }} in architecture ${{ runner.arch }}"

    - name: Print checkout information
      run: echo "Checkout of a repository ${{ github.repository }} and branch ${{ github.ref }}"
    
    - name: Checkout solution code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: List files in the root
      run: |
        ls ${{ github.workspace }}
 
    - name: Build solution
      run: dotnet build TodoApi.sln --configuration Release

    - name: Test solution
      run: dotnet test TodoApi.sln --configuration Release --no-build

    - name: Use local Metadata action
      uses: ./.github/actions/metadata/action.yml

    - name: Add executable permissions to local file
      run: |
        chmod +x ./scripts/test.sh
        ./scripts/test.sh

    - name: Print job status
      run: echo "The job's status is ${{ job.status }}"

    - shell: bash
      run: |
        echo "Test" > out.txt

    - name: Upload a file
      uses: actions/upload-artifact@v4
      with:
          name: out-file
          path: out.txt
