name: Main forkflow
run-name: Called by ${{ github.actor }}

on:
  push:
    branches:
      - 'master'
      - 'dev/**'
  pull_request:
    types:
      - opened

jobs:

  build-and-test-solution:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:

    - name: Checkout solution code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
 
    - name: Build solution
      run: dotnet build TodoApi.sln --configuration Release

    - name: Test solution
      run: dotnet test TodoApi.sln --configuration Release --no-build
