name: Development main workflow

on:
  pull_request:
    types: opened
  workflow_dispatch:

jobs:
  build-and-test-solution:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout solution code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Build solution
      run: dotnet build TodoApi.sln --configuration Release

    - name: Test solution
      run: dotnet test TodoApi.sln --configuration Release --no-build
