name: Development main workflow

on:
  pull_request:
    types: opened
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: todo-api
  BUILD_ID: ${{ github.run_id }}
  GITHUB_LOGIN: ${{ github.actor }}

jobs:
  build-and-test-solution:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout solution code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0'

    - name: Build solution
      run: dotnet build TodoApi.sln --configuration Release

    - name: Test solution
      run: dotnet test TodoApi.sln --configuration Release --no-build

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry - ghcr.io
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image of TodoApi
      uses: docker/build-push-action@master
      with:
        context: .
        file: ./TodoApi/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.GITHUB_LOGIN }}/${{ env.IMAGE_NAME }}:v0.${{ env.BUILD_ID }}
        build-args: |
          OUTPUT_PATH='/Out'

  build-and-publish-images:
    runs-on: ubuntu-latest
    if: success()
    needs: build-and-test-solution
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        