name: secret-scanning-git-leaks

on:
  workflow_run:
    workflows: [ "Main forkflow" ]

jobs:
  scan:
    name: git-leaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
