name: Semgrep SAST scan

on:
  workflow_run:
    workflows: [ "Main forkflow" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
