name: wapiti DAST scan

on:
  
  workflow_run:
    workflows: [ "Main forkflow" ]
    types:
      - completed
  workflow_dispatch: {}

jobs:

  build-and-run-application:

    name: Buil and run application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
        
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Build solution
        run: dotnet build TodoApi.sln --configuration Release

      - name: Start Todo.Web.Server project
        run: dotnet run --project Todo.Web.Server.csproj --configuration Release &
        working-directory: ./Todo.Web/Server/

      - name: Start TodoApi project
        run: dotnet run --project TodoApi.csproj --configuration Release &
        working-directory: ./TodoApi/

      - name: Start DAST scan
        continue-on-error: false
        run: |
          sudo apt install wapiti
          wapiti --module all --url http://0.0.0.0:5147 --verbose 2

      - name: Find wapiti HTML report
        id: find-report
        run: |
          # Find wapiti HTML report
          HTML_FILE=$(find /home/runner/.wapiti/generated_report/ -type f -name "0.0.0.0_5147_*.html" -print -quit)
          # ::set-output sets output variable within step
          echo "::set-output name=report-path::$HTML_FILE"

      - name: Archive wapiti DAST HTML report
        uses: actions/upload-artifact@v4
        with:
          name: wapiti-dast-html-report
          path: ${{ steps.find-report.outputs.report-path }}
