name: wapiti DAST scan
run-name: Called by ${{ github.actor }}

on:
  
  workflow_run:
    workflows: [ "Main forkflow" ]
    types:
      - completed
  workflow_dispatch: {}

jobs:

  build-and-run-application:

    name: Buil and run application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
        
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Build solution
        run: dotnet build TodoApi.sln --configuration Release

      - name: Start Todo.Web.Server project
        run: dotnet run --project Todo.Web.Server.csproj --configuration Release &
        working-directory: ./Todo.Web/Server/

      - name: Start TodoApi project
        run: dotnet run --project TodoApi.csproj --configuration Release &
        working-directory: ./TodoApi/

  wapiti-dynamic-vulnerabilities-scan:

    needs: build-and-run-application
    name: DAST scan
    runs-on: ubuntu-latest

    steps:

    - name: Start DAST scan
      continue-on-error: true
      run: |
        apt install wapiti
        wapiti --module all --url https://localhost:7123/ --verbose 2
