name: zap2docker DAST scan
run-name: Called by ${{ github.actor }}

on:
  
  workflow_run:
    workflows: [ "Main forkflow" ]
    types:
      - completed
  workflow_dispatch: {}

jobs:

  build-and-run-application:
    name: Buil and run application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Build solution
        run: dotnet build TodoApi.sln --configuration Release
  
      - name: Start Todo.Web.Server project
        run: dotnet run --project Todo.Web.Server --configuration Release
      
      - name: Start TodoApi project
        run: dotnet run --project TodoApi --configuration Release

  zap2docker-api-scan:
    needs: build-and-run-application
    name: API scan
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
    steps:
    - name: Start TodoApi project
      run: zap-api-scan.py -t https://localhost:5001/swagger/v1/swagger.json-f openapi
